language: java
jdk:
  - oraclejdk8
addons:
  postgresql: "9.4"
install:
  - mvn install -DskipTests -DskipWildfly
before_script:
  - psql -c "create user chouette with login createdb superuser encrypted  password 'chouette';" -U postgres
  - psql -c 'create database chouette_test with owner = chouette;' -U postgres
